// Razorpay script and client redirection helpers
import { APIError, createPaymentOrder } from './api';
import { requireConsent } from './consent';
import { clerkEnabled } from './clerk';

export class CheckoutAuthRequiredError extends Error {
  constructor() {
    super('sign_in_required');
    this.name = 'CheckoutAuthRequiredError';
  }
}

export class ActivePlanConflictError extends Error {
  activePlanCode: string;
  remainingPercent: number;
  dashboardUrl: string;

  constructor(message: string, data: Record<string, unknown> = {}) {
    super(message);
    this.name = 'ActivePlanConflictError';
    this.activePlanCode = typeof data.active_plan_code === 'string' ? data.active_plan_code : '';
    this.remainingPercent = typeof data.remaining_budget_percent === 'number' ? data.remaining_budget_percent : 0;
    this.dashboardUrl = typeof data.dashboard_url === 'string' ? data.dashboard_url : '/dashboard';
  }
}

export function checkoutErrorMessage(error: unknown): string {
  if (error instanceof ActivePlanConflictError) {
    const plan = error.activePlanCode || 'A plan';
    const budget = error.remainingPercent > 0 ? ` (${error.remainingPercent}% budget left)` : '';
    return `${plan} is already active${budget}. Open your dashboard to use it before buying another pass.`;
  }
  if (error instanceof APIError && error.status === 409) {
    return error.message;
  }
  if (error instanceof APIError && error.status === 412) {
    return 'Please accept the Terms, Privacy, and Refund policies before checkout.';
  }
  if (error instanceof Error) return error.message;
  return 'unknown error';
}

export async function redirectToCheckout(planCode: string): Promise<void> {
  // Explicit, non-pre-ticked consent to Terms/Privacy/Refund is required before
  // any payment. Throws 'consent_declined' if the user cancels — callers ignore it.
  await requireConsent();
  try {
    const paymentUrl = await createPaymentOrder(planCode);
    if (!paymentUrl) {
      throw new Error('Payment URL not generated by gateway');
    }
    // Redirect the developer to the secure checkout page hosted by Razorpay
    window.location.href = paymentUrl;
  } catch (error) {
    if (error instanceof APIError && error.status === 401) {
      throw new CheckoutAuthRequiredError();
    }
    if (error instanceof APIError && error.status === 409 && error.code === 'active_plan_conflict') {
      throw new ActivePlanConflictError(error.message, error.data);
    }
    throw error;
  }
}

export function checkoutRequiresSignIn(): boolean {
  return clerkEnabled;
}
