import type { ArtifactKind } from './shared.js';
import type { SkillId } from './skills.js';
import type { TemplateSource, WorkbenchTemplate } from './workbenchTemplates.js';

export type TemplateAudience = 'student' | 'college' | 'professional' | 'investor';

export type PremiumTemplateSeed = {
  id: string;
  name: string;
  category: string;
  format: ArtifactKind;
  skillId: SkillId;
  audience: TemplateAudience;
  thumbFolder: 'pptx' | 'excel' | 'pdf' | 'resume';
  thumbIndex: number;
  sourceUrl: string;
  description: string;
  useCase: string;
  source: TemplateSource;
  tags: string[];
  designPreset?: string;
  scaffoldId?: string;
  visualDirection?: string;
  visualStyle: string;
  structureHints?: string[];
  featured?: boolean;
  sortOrder: number;
  starterPrompt: string;
};

const MS_PPT = 'https://powerpoint.cloud.microsoft/create/en/';
const MS_XLS = 'https://excel.cloud.microsoft/create/en/templates/';
const MS_WORD = 'https://word.cloud.microsoft/create/en/templates/';
const MS_PITCH = 'https://powerpoint.cloud.microsoft/create/en/pitch-deck-templates/';
const MS_EDU = 'https://powerpoint.cloud.microsoft/create/en/education-templates/';
const SLIDESGO = 'https://slidesgo.com/';
const CANVA = 'https://www.canva.com/presentations/templates/';
const PITCH = 'https://pitch.com/templates/';

/** Premium catalog mapped to peak-reference aesthetics and 2025–2026 gallery research. */
export const premiumTemplateCatalog: PremiumTemplateSeed[] = [
  // —— INVESTOR / PITCH DECKS (lime metrics, dark cinematic — pptx peak refs) ——
  {
    id: 'premium-sequoia-signal',
    name: 'Sequoia Signal Seed',
    category: 'Investor pitch',
    format: 'deck',
    skillId: 'ppt',
    audience: 'investor',
    thumbFolder: 'pptx',
    thumbIndex: 1,
    sourceUrl: MS_PITCH,
    description: 'Editorial ivory investor arc with one-insight-per-slide discipline and single-chart proof slides.',
    useCase: 'Pre-seed and seed fundraising following classic VC narrative structure.',
    source: 'workbench-curated',
    tags: ['investor', 'seed', 'sequoia', 'editorial'],
    designPreset: 'editorial-ivory',
    scaffoldId: 'investor-12',
    visualStyle: 'Editorial ivory with restrained serif headlines and metric-forward chart slides',
    structureHints: ['One chart equals one insight per slide', 'End with a crisp fundraising ask'],
    featured: true,
    sortOrder: 110,
    starterPrompt: 'Create a 12-slide seed investor deck with thesis, market, product, traction, team, and ask.'
  },
  {
    id: 'premium-midnight-launch',
    name: 'Midnight Launch 2026',
    category: 'Startup pitch',
    format: 'deck',
    skillId: 'ppt',
    audience: 'investor',
    thumbFolder: 'pptx',
    thumbIndex: 5,
    sourceUrl: PITCH,
    description: 'Dark graphite launch deck with neon lime CTAs and glassmorphism metric tiles.',
    useCase: 'Series A SaaS pitch with cinematic dark-mode polish.',
    source: 'workbench-curated',
    tags: ['startup', 'dark', 'saas', 'launch'],
    designPreset: 'midnight-aurora',
    scaffoldId: 'investor-12',
    visualStyle: 'Dark cinematic with lime metric blocks and high-contrast evidence tiles',
    featured: true,
    sortOrder: 111,
    starterPrompt: 'Create a dark-mode startup pitch deck with traction metrics, market sizing, and use-of-funds.'
  },
  {
    id: 'premium-lime-sales-warroom',
    name: 'Lime Metric Sales War Room',
    category: 'Sales deck',
    format: 'deck',
    skillId: 'ppt',
    audience: 'professional',
    thumbFolder: 'pptx',
    thumbIndex: 1,
    sourceUrl: 'https://powerpoint.cloud.microsoft/create/en/sales-presentations/',
    description: 'Pipeline funnel cards with bold geometric headlines and quota attainment charts.',
    useCase: 'Weekly sales standup translating CRM data into forecast stories.',
    source: 'microsoft-create',
    tags: ['sales', 'pipeline', 'metrics', 'lime'],
    designPreset: 'signal-orange',
    visualStyle: 'Lime metric blocks with pipeline funnel cards and bold geometric headlines',
    featured: false,
    sortOrder: 112,
    starterPrompt: 'Create a sales war-room deck with pipeline stages, quota attainment, and win/loss analysis.'
  },
  {
    id: 'premium-financial-close',
    name: 'Financial Close Investor Update',
    category: 'Financial deck',
    format: 'deck',
    skillId: 'ppt',
    audience: 'investor',
    thumbFolder: 'pptx',
    thumbIndex: 4,
    sourceUrl: 'https://powerpoint.cloud.microsoft/create/en/financial-presentations/',
    description: 'Monthly investor update with burn, runway, cohort retention, and hiring plan slides.',
    useCase: 'CFO and founder monthly investor letter deck.',
    source: 'microsoft-create',
    tags: ['finance', 'investor', 'monthly', 'kpi'],
    designPreset: 'consulting-mono',
    visualStyle: 'Tabular KPI strips with waterfall charts and conservative serif accents',
    featured: false,
    sortOrder: 113,
    starterPrompt: 'Create a monthly investor update deck with MRR, burn, runway, cohorts, and hiring plan.'
  },
  {
    id: 'premium-product-launch-reel',
    name: 'Product Launch Hero Reel',
    category: 'Product launch',
    format: 'deck',
    skillId: 'ppt',
    audience: 'professional',
    thumbFolder: 'pptx',
    thumbIndex: 6,
    sourceUrl: 'https://powerpoint.cloud.microsoft/create/en/keynote-templates/',
    description: 'Go-to-market reveal with device mockups, feature callouts, and rollout calendar.',
    useCase: 'Product GTM kickoff with pricing tiers and channel plan.',
    source: 'microsoft-create',
    tags: ['product', 'gtm', 'launch', 'keynote'],
    designPreset: 'noir-lumina',
    visualStyle: 'Device mockup frames with feature-callout pills and premium SaaS card layouts',
    featured: true,
    sortOrder: 114,
    starterPrompt: 'Create a product launch deck with positioning, feature highlights, pricing, and GTM rollout.'
  },
  {
    id: 'premium-transformative-board',
    name: 'Transformative Teal Boardroom',
    category: 'Board briefing',
    format: 'deck',
    skillId: 'ppt',
    audience: 'investor',
    thumbFolder: 'pptx',
    thumbIndex: 3,
    sourceUrl: PITCH,
    description: 'Calm board review with teal KPI accents, soft-curve cards, and AA-accessible contrast.',
    useCase: 'Quarterly board review with executive-ready metrics.',
    source: 'workbench-curated',
    tags: ['board', 'teal', 'quarterly', 'kpi'],
    designPreset: 'executive-slate',
    scaffoldId: 'board-8',
    visualStyle: 'Restorative neutrals with teal KPI accents and soft-curve metric cards',
    featured: true,
    sortOrder: 115,
    starterPrompt: 'Create an 8-slide board briefing with BLUF, risks, evidence, decision, and plan slides.'
  },
  {
    id: 'premium-brix-agency',
    name: 'Brix Agency Case Study',
    category: 'Agency pitch',
    format: 'deck',
    skillId: 'ppt',
    audience: 'professional',
    thumbFolder: 'pptx',
    thumbIndex: 2,
    sourceUrl: CANVA,
    description: 'Asymmetric portfolio grids with oversized grotesk type and full-bleed client proof.',
    useCase: 'Agency new-business pitch with ROI case studies.',
    source: 'canva',
    tags: ['agency', 'portfolio', 'case-study', 'creative'],
    designPreset: 'cobalt-bold',
    visualStyle: 'Asymmetric grids with oversized type and full-bleed portfolio spreads',
    featured: false,
    sortOrder: 116,
    starterPrompt: 'Create an agency pitch deck with client logos, before/after case studies, and ROI proof.'
  },
  {
    id: 'premium-consulting-strategy',
    name: 'Consulting Strategy Arc',
    category: 'Strategy deck',
    format: 'deck',
    skillId: 'ppt',
    audience: 'professional',
    thumbFolder: 'pptx',
    thumbIndex: 4,
    sourceUrl: CANVA,
    description: 'MBB-style strategy deck with issue trees, 2x2 frameworks, and implementation roadmap.',
    useCase: 'Strategy recommendation for C-suite decision makers.',
    source: 'canva',
    tags: ['consulting', 'strategy', 'framework', 'mckinsey'],
    designPreset: 'consulting-mono',
    visualStyle: 'Navy and sand palette with 2x2 framework matrices and icon-led dividers',
    featured: false,
    sortOrder: 117,
    starterPrompt: 'Create a strategy recommendation deck with issue tree, options analysis, and roadmap.'
  },
  // —— CAMPUS / STUDENT DECKS ——
  {
    id: 'premium-campus-election',
    name: 'Campus Club Election',
    category: 'Campus presentation',
    format: 'deck',
    skillId: 'ppt',
    audience: 'college',
    thumbFolder: 'pptx',
    thumbIndex: 6,
    sourceUrl: MS_EDU,
    description: 'Student government campaign with platform pillars, budget ask, and authentic campus photography.',
    useCase: 'Club officer or student government election campaigns.',
    source: 'microsoft-create',
    tags: ['campus', 'election', 'student', 'club'],
    designPreset: 'bold-pop',
    visualStyle: 'Authentic campus photography with hand-drawn badges and high-contrast manifesto type',
    featured: false,
    sortOrder: 120,
    starterPrompt: 'Create a campus election deck with platform pillars, budget proposal, and team introduction.'
  },
  {
    id: 'premium-aesthetic-portfolio',
    name: 'Aesthetic Class Portfolio',
    category: 'Student portfolio',
    format: 'deck',
    skillId: 'ppt',
    audience: 'student',
    thumbFolder: 'pptx',
    thumbIndex: 5,
    sourceUrl: 'https://powerpoint.cloud.microsoft/create/en/aesthetic-slides/',
    description: 'End-of-term visual portfolio with soft gradients, polaroid frames, and scrapbook layering.',
    useCase: 'Art, design, or communications coursework portfolio.',
    source: 'microsoft-create',
    tags: ['portfolio', 'aesthetic', 'student', 'creative'],
    designPreset: 'bold-pop',
    visualStyle: 'Soft gradients with polaroid frames and scrapbook layering',
    featured: false,
    sortOrder: 121,
    starterPrompt: 'Create a visual class portfolio deck with project highlights, process notes, and reflection.'
  },
  {
    id: 'premium-presentation-trends-2026',
    name: 'Presentation Trends 2026',
    category: 'Design-forward deck',
    format: 'deck',
    skillId: 'ppt',
    audience: 'college',
    thumbFolder: 'pptx',
    thumbIndex: 3,
    sourceUrl: `${SLIDESGO}presentation-trends-2026`,
    description: 'Asymmetric layouts with teal accent KPIs and video placeholder frames.',
    useCase: 'Communications assignment teaching current presentation best practices.',
    source: 'workbench-curated',
    tags: ['trends', '2026', 'design', 'communications'],
    designPreset: 'noir-lumina',
    visualStyle: 'Asymmetric depth layouts with transformative teal accents',
    featured: false,
    sortOrder: 122,
    starterPrompt: 'Create a design-forward presentation on a topic of my choice using 2026 layout trends.'
  },
  // —— REPORTS / PDF (editorial ivory — pdf peak refs) ——
  {
    id: 'premium-brand-codex',
    name: 'Brand Guidelines Codex',
    category: 'Brand guide',
    format: 'report',
    skillId: 'pdf',
    audience: 'professional',
    thumbFolder: 'pdf',
    thumbIndex: 1,
    sourceUrl: MS_WORD,
    description: 'Living brand book with logo clear-space, color tokens, type specimens, and voice rules.',
    useCase: 'Brand kits, client onboarding, creative handoffs.',
    source: 'microsoft-create',
    tags: ['brand', 'guidelines', 'codex', 'visual'],
    designPreset: 'editorial-ivory',
    visualStyle: 'Swatch grids with logo clear-space diagrams and editorial ivory section cards',
    visualDirection: 'Premium editorial layout with generous whitespace and structured section cards like Turis brand storytelling.',
    featured: true,
    sortOrder: 130,
    starterPrompt: 'Create a brand guidelines PDF with logo usage, color palette, typography, and voice guidelines.'
  },
  {
    id: 'premium-white-paper',
    name: 'White Paper Thought Leadership',
    category: 'White paper',
    format: 'report',
    skillId: 'pdf',
    audience: 'professional',
    thumbFolder: 'pdf',
    thumbIndex: 2,
    sourceUrl: MS_WORD,
    description: 'B2B authority piece with pull-quote sidebars and data-callout inset boxes.',
    useCase: 'Gated PDF lead magnet from market research.',
    source: 'microsoft-create',
    tags: ['white-paper', 'b2b', 'thought-leadership'],
    designPreset: 'editorial-ivory',
    visualStyle: 'Long-form serif with pull-quote sidebars and data-callout inset boxes',
    featured: false,
    sortOrder: 131,
    starterPrompt: 'Create a white paper with executive summary, market analysis, and actionable recommendations.'
  },
  {
    id: 'premium-one-pager-brief',
    name: 'One-Pager Executive Brief',
    category: 'One-pager',
    format: 'report',
    skillId: 'pdf',
    audience: 'investor',
    thumbFolder: 'pdf',
    thumbIndex: 3,
    sourceUrl: MS_WORD,
    description: 'Compressed investment teaser with hero stat band designed for email forwardability.',
    useCase: 'Partnership or investment teaser for busy executives.',
    source: 'workbench-curated',
    tags: ['one-pager', 'executive', 'teaser', 'investor'],
    designPreset: 'executive-slate',
    visualStyle: 'Single-page grid with hero stat band and scannable section hierarchy',
    featured: true,
    sortOrder: 132,
    starterPrompt: 'Create a one-page executive brief with problem, solution, traction metrics, and next step.'
  },
  {
    id: 'premium-board-dossier',
    name: 'Board Report Dossier',
    category: 'Board report',
    format: 'report',
    skillId: 'pdf',
    audience: 'investor',
    thumbFolder: 'pdf',
    thumbIndex: 4,
    sourceUrl: PITCH,
    description: 'Formal board packet with financials, OKRs, RAG status pills, and appendix exhibits.',
    useCase: 'Monthly board data room export aligned with deck metrics.',
    source: 'workbench-curated',
    tags: ['board', 'dossier', 'okrs', 'financials'],
    designPreset: 'executive-slate',
    scaffoldId: 'executive-memo',
    visualStyle: 'Tabular board metrics with RAG status pills and appendix exhibits',
    featured: false,
    sortOrder: 133,
    starterPrompt: 'Create a board report PDF with financials, OKR progress, risks, and strategic decisions.'
  },
  {
    id: 'premium-skincare-guide',
    name: 'Personalized Guide PDF',
    category: 'Brand guide',
    format: 'report',
    skillId: 'pdf',
    audience: 'professional',
    thumbFolder: 'pdf',
    thumbIndex: 5,
    sourceUrl: MS_WORD,
    description: 'Multi-section personalized guide with product grids, progress tracking, and membership CTAs.',
    useCase: 'Client onboarding guides, wellness programs, or service playbooks.',
    source: 'workbench-curated',
    tags: ['guide', 'personalized', 'multi-section', 'premium'],
    designPreset: 'wellness-signal',
    visualStyle: 'Clean white cards on soft backgrounds with product photography and progress grids',
    visualDirection: 'Hi.skin-style personalized guide with AM/PM routines, progress tracking, and membership offers.',
    featured: true,
    sortOrder: 134,
    starterPrompt: 'Create a personalized client guide PDF with profile sections, recommendations, and progress tracking.'
  },
  {
    id: 'premium-grant-brief',
    name: 'Grant Application Brief',
    category: 'Grant proposal',
    format: 'report',
    skillId: 'proposal',
    audience: 'professional',
    thumbFolder: 'pdf',
    thumbIndex: 2,
    sourceUrl: MS_WORD,
    description: 'Nonprofit grant submission with theory of change, outcome metrics, and budget justification.',
    useCase: 'Research or nonprofit grant applications.',
    source: 'microsoft-create',
    tags: ['grant', 'nonprofit', 'impact', 'proposal'],
    designPreset: 'editorial-warm',
    visualStyle: 'Outcome metric tiles with beneficiary photography and budget justification tables',
    featured: false,
    sortOrder: 135,
    starterPrompt: 'Create a grant application brief with theory of change, outcomes, budget, and evaluation plan.'
  },
  // —— EXCEL / SHEETS (grid invoice aesthetic — excel peak refs) ——
  {
    id: 'premium-saas-metrics',
    name: 'SaaS Metrics Dashboard',
    category: 'KPI dashboard',
    format: 'sheet',
    skillId: 'xlsx',
    audience: 'investor',
    thumbFolder: 'excel',
    thumbIndex: 3,
    sourceUrl: MS_XLS,
    description: 'Startup KPI cockpit with MRR, churn, CAC, LTV, and burn multiple tiles.',
    useCase: 'Founder and investor metrics tracking.',
    source: 'microsoft-create',
    tags: ['saas', 'mrr', 'churn', 'dashboard'],
    designPreset: 'lime-metric',
    visualStyle: 'Lime metric blocks with MRR/ARR tiles and cohort retention heatmap',
    featured: true,
    sortOrder: 140,
    starterPrompt: 'Create a SaaS metrics dashboard with MRR, churn, CAC, LTV, and burn multiple calculations.'
  },
  {
    id: 'premium-cap-table',
    name: 'Cap Table Dilution Model',
    category: 'Cap table',
    format: 'sheet',
    skillId: 'xlsx',
    audience: 'investor',
    thumbFolder: 'excel',
    thumbIndex: 4,
    sourceUrl: MS_XLS,
    description: 'Seed-to-Series B cap table with SAFE conversions and pro-rata scenario tabs.',
    useCase: 'Fundraising dilution modeling for founders.',
    source: 'microsoft-create',
    tags: ['cap-table', 'dilution', 'safe', 'fundraising'],
    designPreset: 'cobalt-bold',
    visualStyle: 'Ownership waterfall with option-pool shading and round scenario tabs',
    featured: true,
    sortOrder: 141,
    starterPrompt: 'Create a cap table spreadsheet with ownership percentages, option pool, and round scenarios.'
  },
  {
    id: 'premium-semester-planner',
    name: 'Semester Course Planner',
    category: 'Student planner',
    format: 'sheet',
    skillId: 'xlsx',
    audience: 'college',
    thumbFolder: 'excel',
    thumbIndex: 5,
    sourceUrl: MS_XLS,
    description: 'Week-grid semester organizer with exam countdown and GPA estimator.',
    useCase: 'College semester planning and assignment tracking.',
    source: 'microsoft-create',
    tags: ['semester', 'planner', 'college', 'gpa'],
    designPreset: 'bold-pop',
    visualStyle: 'Week-grid blocks with exam countdown and course color bands',
    featured: false,
    sortOrder: 142,
    starterPrompt: 'Create a semester planner with courses, assignment due dates, exam schedule, and GPA tracker.'
  },
  {
    id: 'premium-event-budget',
    name: 'Campus Event Budget',
    category: 'Event budget',
    format: 'sheet',
    skillId: 'xlsx',
    audience: 'college',
    thumbFolder: 'excel',
    thumbIndex: 6,
    sourceUrl: MS_XLS,
    description: 'Hackathon or fest budget with sponsor offsets, vendor lines, and cost-per-attendee.',
    useCase: 'Campus event planning and finance tracking.',
    source: 'microsoft-create',
    tags: ['event', 'campus', 'budget', 'hackathon'],
    designPreset: 'rose-editorial',
    visualStyle: 'Vendor line items with sponsor offset column and contingency row',
    featured: false,
    sortOrder: 143,
    starterPrompt: 'Create a campus event budget with vendor costs, sponsor revenue, and per-attendee metrics.'
  },
  {
    id: 'premium-sales-pipeline',
    name: 'Sales Pipeline Tracker',
    category: 'Sales pipeline',
    format: 'sheet',
    skillId: 'xlsx',
    audience: 'professional',
    thumbFolder: 'excel',
    thumbIndex: 7,
    sourceUrl: MS_XLS,
    description: 'B2B deal board with stage probabilities, weighted forecast, and quota attainment.',
    useCase: 'Sales team CRM-style pipeline management.',
    source: 'microsoft-create',
    tags: ['sales', 'pipeline', 'forecast', 'crm'],
    designPreset: 'spreadsheet-royal',
    visualStyle: 'Stage-column kanban with weighted forecast and win-rate sparkline',
    featured: false,
    sortOrder: 144,
    starterPrompt: 'Create a sales pipeline tracker with deal stages, amounts, probabilities, and forecast.'
  },
  {
    id: 'premium-student-loan',
    name: 'Student Loan vs Invest',
    category: 'Student finance',
    format: 'sheet',
    skillId: 'xlsx',
    audience: 'student',
    thumbFolder: 'excel',
    thumbIndex: 1,
    sourceUrl: MS_XLS,
    description: 'Comparison model for loan payoff versus investment with interest scenarios.',
    useCase: 'Personal finance decisions for students and early-career professionals.',
    source: 'microsoft-create',
    tags: ['student', 'loan', 'finance', 'calculator'],
    designPreset: 'spreadsheet-forest',
    visualStyle: 'Green header comparison table with payoff calculations and scenario tabs',
    featured: false,
    sortOrder: 145,
    starterPrompt: 'Create a student loan payoff vs investment comparison spreadsheet with scenarios.'
  },
  {
    id: 'premium-wedding-budget',
    name: 'Wedding Budget Summary',
    category: 'Personal budget',
    format: 'sheet',
    skillId: 'xlsx',
    audience: 'college',
    thumbFolder: 'excel',
    thumbIndex: 2,
    sourceUrl: MS_XLS,
    description: 'Elegant wedding budget with category pie chart and expense tracking.',
    useCase: 'Personal event planning with category breakdowns.',
    source: 'microsoft-create',
    tags: ['wedding', 'budget', 'personal', 'planner'],
    designPreset: 'editorial-warm',
    visualStyle: 'Elegant typography with pie chart allocation and expense category bands',
    featured: false,
    sortOrder: 146,
    starterPrompt: 'Create a wedding budget spreadsheet with categories, estimates, actuals, and variance.'
  },
  {
    id: 'premium-job-candidates',
    name: 'Job Candidates Tracker',
    category: 'Hiring tracker',
    format: 'sheet',
    skillId: 'xlsx',
    audience: 'professional',
    thumbFolder: 'excel',
    thumbIndex: 7,
    sourceUrl: MS_XLS,
    description: 'Hiring pipeline with candidate status, role fit, and interview stage columns.',
    useCase: 'HR and hiring manager candidate tracking.',
    source: 'microsoft-create',
    tags: ['hiring', 'candidates', 'hr', 'recruiting'],
    designPreset: 'signal-orange',
    visualStyle: 'Red header hiring table with status chips and candidate info columns',
    featured: false,
    sortOrder: 147,
    starterPrompt: 'Create a job candidates tracker with name, role, status, and interview notes.'
  },
  // —— RESUMES (peak resume refs) ——
  {
    id: 'premium-social-media-cv',
    name: 'Social Media Manager CV',
    category: 'Marketing resume',
    format: 'resume',
    skillId: 'resume',
    audience: 'professional',
    thumbFolder: 'resume',
    thumbIndex: 1,
    sourceUrl: MS_WORD,
    description: 'Senior marketing resume with engagement stat chips and campaign highlight cards.',
    useCase: 'Social media and growth marketing roles.',
    source: 'microsoft-create',
    tags: ['marketing', 'social', 'resume', 'metrics'],
    designPreset: 'modern-indigo',
    visualStyle: 'Engagement stat chips with elegant sans and campaign highlight cards',
    featured: true,
    sortOrder: 150,
    starterPrompt: 'Create a social media manager resume using only supplied facts with measurable campaign outcomes.'
  },
  {
    id: 'premium-big-data-cv',
    name: 'Big Data Engineer CV',
    category: 'Tech resume',
    format: 'resume',
    skillId: 'resume',
    audience: 'professional',
    thumbFolder: 'resume',
    thumbIndex: 2,
    sourceUrl: MS_WORD,
    description: 'Engineering resume with summary band, project highlights, and technical skill tags.',
    useCase: 'Data engineering and quality engineering roles.',
    source: 'workbench-curated',
    tags: ['engineering', 'data', 'tech', 'resume'],
    designPreset: 'modern-indigo',
    visualStyle: 'Summary paragraph with project highlights and mono skill tags',
    featured: false,
    sortOrder: 151,
    starterPrompt: 'Create a big data engineer resume with summary, experience bullets, and technical skills.'
  },
  {
    id: 'premium-campus-placement',
    name: 'Campus Placement Sprint',
    category: 'Campus resume',
    format: 'resume',
    skillId: 'resume',
    audience: 'college',
    thumbFolder: 'resume',
    thumbIndex: 3,
    sourceUrl: 'https://word.cloud.microsoft/create/en/resume-builder/',
    description: 'One-page compact resume with project links and internship chronology for campus recruiting.',
    useCase: 'Final-year on-campus placement and internship conversion.',
    source: 'microsoft-create',
    tags: ['campus', 'placement', 'internship', 'ats'],
    designPreset: 'classic-ats',
    visualStyle: 'One-page compact with project links row and internship chronology',
    featured: true,
    sortOrder: 152,
    starterPrompt: 'Create a campus placement resume using only supplied facts with projects and internships.'
  },
  {
    id: 'premium-tech-stack-ats',
    name: 'Tech Stack Engineer ATS',
    category: 'CS graduate resume',
    format: 'resume',
    skillId: 'resume',
    audience: 'college',
    thumbFolder: 'resume',
    thumbIndex: 4,
    sourceUrl: 'https://word.cloud.microsoft/create/en/ats-templates/',
    description: 'CS graduate resume tuned for FAANG-style ATS keyword matching.',
    useCase: 'Computer science graduates targeting tech companies.',
    source: 'microsoft-create',
    tags: ['cs', 'ats', 'faang', 'graduate'],
    designPreset: 'classic-ats',
    visualStyle: 'Mono skill tags with project repo links and leetcode-neutral layout',
    featured: false,
    sortOrder: 153,
    starterPrompt: 'Create an ATS-friendly CS graduate resume with projects, skills, and internships.'
  },
  {
    id: 'premium-executive-boardroom-cv',
    name: 'Executive Boardroom CV',
    category: 'Executive resume',
    format: 'resume',
    skillId: 'resume',
    audience: 'professional',
    thumbFolder: 'resume',
    thumbIndex: 5,
    sourceUrl: MS_WORD,
    description: 'C-suite resume with ivory editorial typography and P&L headline band.',
    useCase: 'VP and C-suite leadership roles.',
    source: 'workbench-curated',
    tags: ['executive', 'c-suite', 'leadership', 'resume'],
    designPreset: 'executive-slate',
    visualStyle: 'Ivory editorial with board-adjacent typography and P&L headline band',
    featured: false,
    sortOrder: 154,
    starterPrompt: 'Create an executive resume emphasizing transformation, scale milestones, and P&L ownership.'
  },
  // —— ASSIGNMENTS / SCHOOL ——
  {
    id: 'premium-lab-chronicle',
    name: 'Science Lab Chronicle',
    category: 'Lab report',
    format: 'assignment',
    skillId: 'assignment',
    audience: 'student',
    thumbFolder: 'pdf',
    thumbIndex: 4,
    sourceUrl: `${SLIDESGO}theme/innovative-science-lab`,
    description: 'Undergrad lab report with hypothesis, apparatus, procedure, data tables, and conclusion.',
    useCase: 'Science lab assignments and experiment documentation.',
    source: 'workbench-curated',
    tags: ['lab', 'science', 'experiment', 'student'],
    designPreset: 'editorial-ivory',
    visualStyle: 'Cream lab-paper texture with beaker icons and results table bands',
    featured: true,
    sortOrder: 160,
    starterPrompt: 'Create a lab report with hypothesis, materials, procedure, data, analysis, and conclusion.'
  },
  {
    id: 'premium-thesis-defense',
    name: 'Thesis Defense Ivory',
    category: 'Thesis defense',
    format: 'assignment',
    skillId: 'assignment',
    audience: 'college',
    thumbFolder: 'pdf',
    thumbIndex: 3,
    sourceUrl: `${SLIDESGO}thesis-defense`,
    description: 'Master\'s/PhD defense with literature gap, methodology, findings, and future work sections.',
    useCase: 'Graduate thesis defense presentations and documents.',
    source: 'workbench-curated',
    tags: ['thesis', 'defense', 'graduate', 'research'],
    designPreset: 'editorial-ivory',
    scaffoldId: 'research-brief',
    visualStyle: 'Editorial ivory with chapter dividers and citation footnote rails',
    featured: true,
    sortOrder: 161,
    starterPrompt: 'Create a thesis defense document with literature gap, methodology, findings, and future work.'
  },
  {
    id: 'premium-case-study-framework',
    name: 'Case Study Analysis',
    category: 'Business case',
    format: 'assignment',
    skillId: 'assignment',
    audience: 'college',
    thumbFolder: 'pdf',
    thumbIndex: 5,
    sourceUrl: CANVA,
    description: 'Business school case with situation, SWOT analysis, options, and recommendation.',
    useCase: 'MBA and business school case study assignments.',
    source: 'canva',
    tags: ['case-study', 'mba', 'swot', 'business'],
    designPreset: 'consulting-mono',
    visualStyle: 'Issue tree diagram with SWOT quadrant and recommendation slide',
    featured: false,
    sortOrder: 162,
    starterPrompt: 'Create a business case analysis with situation, SWOT, options, and recommendation.'
  },
  {
    id: 'premium-book-report',
    name: 'Writing Book Reports',
    category: 'Book report',
    format: 'assignment',
    skillId: 'assignment',
    audience: 'student',
    thumbFolder: 'pdf',
    thumbIndex: 1,
    sourceUrl: `${SLIDESGO}theme/writing-book-reports`,
    description: 'Literature assignment with plot summary, character map, theme analysis, and quotes.',
    useCase: 'Middle and high school book report assignments.',
    source: 'workbench-curated',
    tags: ['book-report', 'literature', 'student', 'essay'],
    designPreset: 'editorial-ivory',
    visualStyle: 'Chapter summary cards with character map and quote pull blocks',
    featured: false,
    sortOrder: 163,
    starterPrompt: 'Create a book report covering plot, characters, themes, and critical analysis.'
  },
  {
    id: 'premium-project-charter',
    name: 'Educational Project Charter',
    category: 'Group project',
    format: 'assignment',
    skillId: 'project',
    audience: 'college',
    thumbFolder: 'pdf',
    thumbIndex: 2,
    sourceUrl: `${SLIDESGO}theme/educational-projects-how-to-plan-them`,
    description: 'Capstone group project with scope, RACI matrix, milestones, and deliverables.',
    useCase: 'College capstone and group project planning.',
    source: 'workbench-curated',
    tags: ['capstone', 'group', 'project', 'charter'],
    designPreset: 'editorial-ivory',
    visualStyle: 'Milestone timeline with team role matrix and risk register mini-grid',
    featured: false,
    sortOrder: 164,
    starterPrompt: 'Create a group project charter with scope, team roles, milestones, and deliverables.'
  },
  // —— EMAIL ——
  {
    id: 'premium-investor-pulse',
    name: 'Investor Monthly Pulse',
    category: 'Investor email',
    format: 'email',
    skillId: 'email',
    audience: 'investor',
    thumbFolder: 'pdf',
    thumbIndex: 3,
    sourceUrl: PITCH,
    description: 'Monthly investor email with wins, asks, metric snapshot, and fundraising status.',
    useCase: 'Founder monthly investor update emails.',
    source: 'workbench-curated',
    tags: ['investor', 'monthly', 'update', 'email'],
    designPreset: 'executive-slate',
    visualStyle: 'Metric snapshot table with wins/asks/needs sections',
    featured: false,
    sortOrder: 170,
    starterPrompt: 'Draft a monthly investor update email with wins, metrics, asks, and next milestones.'
  },
  {
    id: 'premium-placement-followup',
    name: 'Campus Placement Follow-Up',
    category: 'Placement email',
    format: 'email',
    skillId: 'email',
    audience: 'college',
    thumbFolder: 'pdf',
    thumbIndex: 4,
    sourceUrl: MS_WORD,
    description: 'Post-interview thank-you with role reference and availability for campus recruiting.',
    useCase: 'Placement season recruiter follow-ups.',
    source: 'microsoft-create',
    tags: ['placement', 'follow-up', 'thank-you', 'campus'],
    designPreset: 'editorial-ivory',
    visualStyle: 'Concise gratitude tone with role-reference line and availability footer',
    featured: false,
    sortOrder: 171,
    starterPrompt: 'Draft a post-interview thank-you email referencing the role and confirming next availability.'
  }
];

export const templateAudienceTabs: Array<{ id: TemplateAudience | 'all'; label: string }> = [
  { id: 'all', label: 'Everyone' },
  { id: 'student', label: 'School' },
  { id: 'college', label: 'College' },
  { id: 'professional', label: 'Pro' },
  { id: 'investor', label: 'Investor' }
];

export function premiumSeedToWorkbenchTemplate(
  seed: PremiumTemplateSeed,
  thumb: (folder: 'pptx' | 'excel' | 'pdf' | 'resume', index: number, max: number) => string,
  thumbMax: Record<'pptx' | 'excel' | 'pdf' | 'resume', number>
): WorkbenchTemplate {
  const audienceLabels: Record<TemplateAudience, string> = {
    student: 'School students and K-12 learners',
    college: 'College students and campus audiences',
    professional: 'Working professionals and business teams',
    investor: 'Investors, boards, and fundraising stakeholders'
  };
  return {
    id: seed.id,
    name: seed.name,
    category: seed.category,
    format: seed.format,
    skillId: seed.skillId,
    thumbnail: thumb(seed.thumbFolder, seed.thumbIndex, thumbMax[seed.thumbFolder]),
    sourceUrl: seed.sourceUrl,
    description: seed.description,
    useCase: seed.useCase,
    source: seed.source,
    tags: [...seed.tags, seed.audience],
    designPreset: seed.designPreset,
    scaffoldId: seed.scaffoldId,
    visualDirection: seed.visualDirection,
    audience: audienceLabels[seed.audience],
    visualStyle: seed.visualStyle,
    structureHints: seed.structureHints,
    featured: seed.featured ?? false,
    sortOrder: seed.sortOrder,
    starterPrompt: seed.starterPrompt
  };
}

export function filterByAudience(
  templates: WorkbenchTemplate[],
  audience: TemplateAudience | 'all'
): WorkbenchTemplate[] {
  if (audience === 'all') return templates;
  return templates.filter((template) => template.tags.includes(audience));
}