// Clerk chrome stripped to match the landing site — flat, no card, no dev footer.
export const delegatorsAuthAppearance = {
  variables: {
    colorPrimary: '#0b0b0c',
    colorBackground: 'transparent',
    colorInputBackground: '#ffffff',
    colorInputText: '#0b0b0c',
    colorText: '#0b0b0c',
    colorTextSecondary: '#57544e',
    colorDanger: '#b91c1c',
    borderRadius: '0.5rem',
    fontFamily: "'General Sans', 'Inter', 'Helvetica Neue', Arial, sans-serif",
    fontSize: '0.9375rem',
  },
  layout: {
    logoPlacement: 'none' as const,
    socialButtonsVariant: 'iconButton' as const,
    socialButtonsPlacement: 'top' as const,
    showOptionalFields: false,
  },
  elements: {
    rootBox: 'w-full',
    cardBox: 'w-full shadow-none bg-transparent',
    card: 'w-full bg-transparent shadow-none border-0 p-0 gap-4',
    header: 'delegators-clerk-hide',
    headerTitle: 'delegators-clerk-hide',
    headerSubtitle: 'delegators-clerk-hide',
    logoBox: 'hidden',
    logoImage: 'hidden',
    socialButtons: 'justify-start gap-3',
    socialButtonsIconButton:
      'h-12 w-12 border border-line bg-white shadow-none transition hover:bg-black/[0.03]',
    socialButtonsIconButtonIcon: 'h-5 w-5',
    dividerRow: 'my-2',
    dividerLine: 'bg-line',
    dividerText: 'text-[11px] font-medium uppercase tracking-[0.14em] text-muted',
    formFieldLabel: 'text-[11px] font-semibold uppercase tracking-[0.14em] text-secondary',
    formFieldInput:
      'h-11 border border-line bg-white text-[15px] shadow-none transition focus:border-[#0b0b0c]/25',
    formButtonPrimary:
      'h-11 bg-[#0b0b0c] text-white text-[15px] font-medium shadow-none transition hover:bg-black/85',
    formButtonReset: 'text-secondary hover:text-foreground',
    footer: 'delegators-clerk-hide',
    footerAction: 'delegators-clerk-hide',
    footerActionText: 'delegators-clerk-hide',
    footerActionLink: 'delegators-clerk-hide',
    identityPreview: 'hidden',
    identityPreviewText: 'hidden',
    identityPreviewEditButton: 'hidden',
    formFieldInputShowPasswordButton: 'text-muted hover:text-foreground',
    alert: 'border border-line bg-white text-secondary text-sm',
    alertText: 'text-secondary',
    otpCodeFieldInput: 'h-11 border border-line',
    formResendCodeLink: 'text-foreground font-medium',
    devBar: 'delegators-clerk-hide',
    developmentModeNotice: 'delegators-clerk-hide',
    badge: 'delegators-clerk-hide',
    main: 'gap-4',
  },
};