import type { ReportArchetype } from './types.js';
import { microsoftReportExpansions } from './microsoftArtifactExpansions.js';

const coreReportArchetypes: ReportArchetype[] = [
  {
    id: 'annual-report',
    title: 'Annual Report 2025',
    category: 'Annual report',
    audience: 'Board members and shareholders',
    tone: 'executive',
    structure: 'annual-report',
    designPreset: 'executive-slate',
    template: 'executive-slate',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    pageSize: 'letter',
    density: 'airy',
    palette: { background: '#F8FAFC', surface: '#E7EDF4', text: '#0F172A', muted: '#64748B', primary: '#1E293B', accent: '#2563EB' },
    orgName: 'Northwind Holdings',
    subject: 'FY2025 performance and outlook'
  },
  {
    id: 'whitepaper',
    title: 'Edge AI Infrastructure Whitepaper',
    category: 'Whitepaper',
    audience: 'Technical decision makers',
    tone: 'professional',
    structure: 'whitepaper',
    designPreset: 'modern-indigo',
    template: 'modern-indigo',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    pageSize: 'a4',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#EEF2FF', text: '#111827', muted: '#6B7280', primary: '#312E81', accent: '#4F46E5' },
    orgName: 'Lattice Systems',
    subject: 'Distributed inference at scale'
  },
  {
    id: 'case-study',
    title: 'Retail Revamp Case Study',
    category: 'Case study',
    audience: 'Prospective enterprise buyers',
    tone: 'professional',
    structure: 'case-study',
    designPreset: 'signal-orange',
    template: 'signal-orange',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#FFF1E8', text: '#23234B', muted: '#6F6F95', primary: '#FF5A1F', accent: '#32327A' },
    orgName: 'Brightline Commerce',
    subject: 'Omnichannel rollout for Meridian Retail'
  },
  {
    id: 'policy-brief',
    title: 'Urban Transit Policy Brief',
    category: 'Policy brief',
    audience: 'City council and policy staff',
    tone: 'professional',
    structure: 'policy-brief',
    designPreset: 'consulting-mono',
    template: 'consulting-mono',
    headingFont: 'Arial',
    bodyFont: 'Arial',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#F2F2F1', text: '#121212', muted: '#6B6B6B', primary: '#1A1A1A', accent: '#C8102E' },
    orgName: 'Metro Policy Lab',
    subject: 'Fare integration and equity impacts'
  },
  {
    id: 'research-memo',
    title: 'Consumer Sentiment Research Memo',
    category: 'Research memo',
    audience: 'Strategy and product leadership',
    tone: 'professional',
    structure: 'research-memo',
    designPreset: 'editorial-ivory',
    template: 'editorial-ivory',
    headingFont: 'Georgia',
    bodyFont: 'Georgia',
    density: 'balanced',
    palette: { background: '#FBF8F1', surface: '#F0E9DB', text: '#221D15', muted: '#7A715F', primary: '#433A2B', accent: '#B5562C' },
    orgName: 'Harbor Insights',
    subject: 'Q2 discretionary spend patterns'
  },
  {
    id: 'brand-guidelines',
    title: 'Brand Guidelines',
    category: 'Brand guide',
    audience: 'Marketing and agency partners',
    tone: 'professional',
    structure: 'brand-guidelines',
    designPreset: 'bold-pop',
    template: 'bold-pop',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'airy',
    palette: { background: '#FFFFFF', surface: '#F3EFFF', text: '#14101F', muted: '#6E6781', primary: '#5B2EFF', accent: '#FF5C00' },
    orgName: 'Pulseform',
    subject: 'Logo, color, typography, and voice'
  },
  {
    id: 'market-analysis',
    title: 'APAC SaaS Market Analysis',
    category: 'Market analysis',
    audience: 'Investors and GTM leaders',
    tone: 'executive',
    structure: 'market-analysis',
    designPreset: 'cobalt-bold',
    template: 'cobalt-bold',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#E8EDFB', text: '#0A1633', muted: '#5A6685', primary: '#1D3FD8', accent: '#4D6FFF' },
    orgName: 'Summit Capital',
    subject: 'Vertical SaaS expansion opportunities'
  },
  {
    id: 'impact-report',
    title: 'Community Impact Report',
    category: 'Impact report',
    audience: 'Donors and community partners',
    tone: 'professional',
    structure: 'impact-report',
    designPreset: 'editorial-warm',
    template: 'editorial-warm',
    headingFont: 'Georgia',
    bodyFont: 'Aptos',
    density: 'airy',
    palette: { background: '#F7F3EC', surface: '#EDE5D8', text: '#262220', muted: '#857B6E', primary: '#3E372F', accent: '#C96F4A' },
    orgName: 'Riverbend Foundation',
    subject: 'Programs, outcomes, and volunteer stories'
  },
  {
    id: 'technical-spec',
    title: 'API Gateway Technical Specification',
    category: 'Technical spec',
    audience: 'Engineering and platform teams',
    tone: 'professional',
    structure: 'technical-spec',
    designPreset: 'midnight-aurora',
    template: 'midnight-aurora',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    pageSize: 'a4',
    density: 'compact',
    palette: { background: '#0B1220', surface: '#16203A', text: '#E6EAF2', muted: '#8B94A8', primary: '#101A30', accent: '#2DD4BF' },
    orgName: 'Atlas Platform',
    subject: 'Auth, routing, and observability contracts'
  },
  {
    id: 'user-manual',
    title: 'Product User Manual',
    category: 'User manual',
    audience: 'End users and support teams',
    tone: 'professional',
    structure: 'user-manual',
    designPreset: 'modern-indigo',
    template: 'modern-indigo',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#F0F9FF', text: '#0C4A6E', muted: '#64748B', primary: '#0369A1', accent: '#38BDF8' },
    orgName: 'Clearpath Software',
    subject: 'Setup, workflows, and troubleshooting'
  },
  {
    id: 'compliance-audit',
    title: 'SOC 2 Compliance Audit Summary',
    category: 'Compliance audit',
    audience: 'Security and compliance officers',
    tone: 'executive',
    structure: 'compliance-audit',
    designPreset: 'consulting-mono',
    template: 'consulting-mono',
    headingFont: 'Arial',
    bodyFont: 'Arial',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#F8FAFC', text: '#0F172A', muted: '#64748B', primary: '#334155', accent: '#DC2626' },
    orgName: 'Sentinel Trust',
    subject: 'Control testing results and remediation'
  },
  {
    id: 'quarterly-review',
    title: 'Q2 Business Review',
    category: 'Quarterly review',
    audience: 'Executive leadership team',
    tone: 'executive',
    structure: 'quarterly-review',
    designPreset: 'executive-slate',
    template: 'executive-slate',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#F1F5F9', surface: '#E2E8F0', text: '#0F172A', muted: '#64748B', primary: '#1E40AF', accent: '#3B82F6' },
    orgName: 'Orion Labs',
    subject: 'Revenue, pipeline, and operating metrics'
  },
  {
    id: 'feasibility-study',
    title: 'Solar Campus Feasibility Study',
    category: 'Feasibility study',
    audience: 'Facilities and finance committees',
    tone: 'professional',
    structure: 'feasibility-study',
    designPreset: 'teal-momentum',
    template: 'editorial-warm',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#ECFDF5', surface: '#D1FAE5', text: '#064E3B', muted: '#047857', primary: '#065F46', accent: '#10B981' },
    orgName: 'Greenfield University',
    subject: 'ROI, permitting, and implementation timeline'
  },
  {
    id: 'grant-proposal',
    title: 'STEM Education Grant Proposal',
    category: 'Grant proposal',
    audience: 'Foundation program officers',
    tone: 'professional',
    structure: 'grant-proposal',
    designPreset: 'rose-editorial',
    template: 'editorial-ivory',
    headingFont: 'Georgia',
    bodyFont: 'Aptos',
    density: 'airy',
    palette: { background: '#FFF5F8', surface: '#FCE7F3', text: '#3F2D33', muted: '#9D7486', primary: '#831843', accent: '#F472B6' },
    orgName: 'Bright Futures Coalition',
    subject: 'After-school maker labs in underserved districts'
  },
  {
    id: 'sustainability-report',
    title: 'Sustainability Report 2025',
    category: 'Sustainability report',
    audience: 'ESG investors and regulators',
    tone: 'executive',
    structure: 'sustainability-report',
    designPreset: 'spreadsheet-forest',
    template: 'executive-slate',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#ECFDF5', text: '#052E1B', muted: '#4B6B5A', primary: '#217346', accent: '#34D399' },
    orgName: 'Evergreen Manufacturing',
    subject: 'Emissions, water use, and supply chain goals'
  },
  {
    id: 'product-brief',
    title: 'Mobile Wallet Product Brief',
    category: 'Product brief',
    audience: 'Product and design teams',
    tone: 'professional',
    structure: 'product-brief',
    designPreset: 'bold-pop',
    template: 'bold-pop',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#FDF4FF', text: '#3B0764', muted: '#7E22CE', primary: '#6B21A8', accent: '#E879F9' },
    orgName: 'Paylane',
    subject: 'Personas, journeys, and MVP scope'
  },
  {
    id: 'competitive-landscape',
    title: 'HR Tech Competitive Landscape',
    category: 'Competitive landscape',
    audience: 'Strategy and sales leadership',
    tone: 'professional',
    structure: 'competitive-landscape',
    designPreset: 'cobalt-bold',
    template: 'cobalt-bold',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#EFF6FF', text: '#1E3A8A', muted: '#60A5FA', primary: '#1D4ED8', accent: '#F59E0B' },
    orgName: 'PeopleStack',
    subject: 'Feature matrix and positioning gaps'
  },
  {
    id: 'onboarding-playbook',
    title: 'Client Onboarding Playbook',
    category: 'Onboarding playbook',
    audience: 'Customer success managers',
    tone: 'professional',
    structure: 'onboarding-playbook',
    designPreset: 'wellness-signal',
    template: 'signal-orange',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'airy',
    palette: { background: '#FFFFFF', surface: '#FFF7ED', text: '#431407', muted: '#9A3412', primary: '#EA580C', accent: '#2563EB' },
    orgName: 'Studio One',
    subject: 'Kickoff, milestones, and health scoring'
  },
  {
    id: 'training-handbook',
    title: 'Sales Training Handbook',
    category: 'Training handbook',
    audience: 'New sales hires and managers',
    tone: 'professional',
    structure: 'training-handbook',
    designPreset: 'noir-lumina',
    template: 'noir-lumina',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#0A0A0C', surface: '#17171C', text: '#F2EFE9', muted: '#9A958C', primary: '#141419', accent: '#E8A33D' },
    orgName: 'Apex Revenue',
    subject: 'Discovery, demo, and negotiation modules'
  },
  {
    id: 'event-program',
    title: 'Innovation Summit Program',
    category: 'Event program',
    audience: 'Attendees and sponsors',
    tone: 'professional',
    structure: 'event-program',
    designPreset: 'lime-metric',
    template: 'bold-pop',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'airy',
    palette: { background: '#FFFFFF', surface: '#F7FEE7', text: '#1A2E05', muted: '#4D7C0F', primary: '#65A30D', accent: '#F97316' },
    orgName: 'Futureworks',
    subject: 'Keynotes, tracks, and networking schedule'
  },
  {
    id: 'newsletter-digest',
    title: 'Product Newsletter Digest',
    category: 'Newsletter digest',
    audience: 'Customers and power users',
    tone: 'professional',
    structure: 'newsletter-digest',
    designPreset: 'editorial-warm',
    template: 'editorial-warm',
    headingFont: 'Georgia',
    bodyFont: 'Aptos',
    density: 'airy',
    palette: { background: '#FFFBEB', surface: '#FEF3C7', text: '#78350F', muted: '#B45309', primary: '#92400E', accent: '#D97706' },
    orgName: 'Threadline',
    subject: 'Release notes, tips, and community highlights'
  },
  {
    id: 'press-kit',
    title: 'Company Press Kit',
    category: 'Press kit',
    audience: 'Media and communications teams',
    tone: 'professional',
    structure: 'press-kit',
    designPreset: 'classic-ats',
    template: 'consulting-mono',
    headingFont: 'Arial',
    bodyFont: 'Arial',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#F5F5F5', text: '#171717', muted: '#737373', primary: '#262626', accent: '#EF4444' },
    orgName: 'Nova Robotics',
    subject: 'Boilerplate, leadership bios, and assets'
  },
  {
    id: 'investor-memo',
    title: 'Series B Investor Memo',
    category: 'Investor memo',
    audience: 'Venture partners and angels',
    tone: 'executive',
    structure: 'investor-memo',
    designPreset: 'midnight-aurora',
    template: 'midnight-aurora',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#0F172A', surface: '#1E293B', text: '#F8FAFC', muted: '#94A3B8', primary: '#0B1220', accent: '#22D3EE' },
    orgName: 'Gridpulse',
    subject: 'Traction, unit economics, and use of funds'
  },
  {
    id: 'legal-brief',
    title: 'Merger Legal Brief',
    category: 'Legal brief',
    audience: 'Legal counsel and executives',
    tone: 'executive',
    structure: 'legal-brief',
    designPreset: 'executive-slate',
    template: 'executive-slate',
    headingFont: 'Georgia',
    bodyFont: 'Georgia',
    pageSize: 'legal',
    density: 'compact',
    palette: { background: '#FAFAF9', surface: '#E7E5E4', text: '#1C1917', muted: '#78716C', primary: '#44403C', accent: '#B91C1C' },
    orgName: 'Summit Legal',
    subject: 'Risk summary and closing conditions'
  },
  {
    id: 'clinical-summary',
    title: 'Clinical Trial Summary',
    category: 'Clinical summary',
    audience: 'Medical reviewers and sponsors',
    tone: 'professional',
    structure: 'clinical-summary',
    designPreset: 'teal-momentum',
    template: 'editorial-warm',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#F0FDFA', surface: '#CCFBF1', text: '#134E4A', muted: '#0F766E', primary: '#115E59', accent: '#14B8A6' },
    orgName: 'Caregrid Research',
    subject: 'Endpoints, safety profile, and next steps'
  },
  {
    id: 'curriculum-guide',
    title: 'Data Science Curriculum Guide',
    category: 'Curriculum guide',
    audience: 'Students and academic advisors',
    tone: 'professional',
    structure: 'curriculum-guide',
    designPreset: 'modern-indigo',
    template: 'modern-indigo',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#EDE9FE', text: '#4C1D95', muted: '#7C3AED', primary: '#5B21B6', accent: '#A78BFA' },
    orgName: 'Campusflow Institute',
    subject: 'Course map, prerequisites, and outcomes'
  },
  {
    id: 'safety-protocol',
    title: 'Warehouse Safety Protocol',
    category: 'Safety protocol',
    audience: 'Operations and safety officers',
    tone: 'professional',
    structure: 'safety-protocol',
    designPreset: 'consulting-mono',
    template: 'consulting-mono',
    headingFont: 'Arial',
    bodyFont: 'Arial',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#FEF2F2', text: '#7F1D1D', muted: '#B91C1C', primary: '#991B1B', accent: '#FBBF24' },
    orgName: 'Routewise Logistics',
    subject: 'PPE, incident response, and audit checklist'
  },
  {
    id: 'project-charter',
    title: 'ERP Migration Project Charter',
    category: 'Project charter',
    audience: 'Steering committee and PMO',
    tone: 'professional',
    structure: 'project-charter',
    designPreset: 'spreadsheet-royal',
    template: 'modern-indigo',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#F5F3FF', text: '#2E1065', muted: '#7C6F9A', primary: '#6B46C1', accent: '#A78BFA' },
    orgName: 'Metro Facilities',
    subject: 'Scope, RACI, timeline, and success criteria'
  },
  {
    id: 'postmortem',
    title: 'Outage Postmortem Report',
    category: 'Postmortem',
    audience: 'Engineering and incident response',
    tone: 'professional',
    structure: 'postmortem',
    designPreset: 'midnight-aurora',
    template: 'midnight-aurora',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#111827', surface: '#1F2937', text: '#F9FAFB', muted: '#9CA3AF', primary: '#030712', accent: '#F87171' },
    orgName: 'Helpline Platform',
    subject: 'Timeline, root cause, and action items'
  },
  {
    id: 'rfp-response',
    title: 'Cloud RFP Response',
    category: 'RFP response',
    audience: 'Procurement and technical evaluators',
    tone: 'professional',
    structure: 'rfp-response',
    designPreset: 'cobalt-bold',
    template: 'cobalt-bold',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#DBEAFE', text: '#1E3A8A', muted: '#3B82F6', primary: '#1D4ED8', accent: '#06B6D4' },
    orgName: 'Sentinel Cloud',
    subject: 'Requirements mapping and implementation plan'
  },
  {
    id: 'style-guide',
    title: 'Editorial Style Guide',
    category: 'Style guide',
    audience: 'Writers and content designers',
    tone: 'professional',
    structure: 'style-guide',
    designPreset: 'editorial-ivory',
    template: 'editorial-ivory',
    headingFont: 'Georgia',
    bodyFont: 'Georgia',
    density: 'airy',
    palette: { background: '#FFFBF5', surface: '#F5EDE3', text: '#292524', muted: '#A8A29E', primary: '#57534E', accent: '#D97706' },
    orgName: 'Harbor Press',
    subject: 'Voice, grammar, and formatting standards'
  },
  {
    id: 'community-report',
    title: 'Neighborhood Community Report',
    category: 'Community report',
    audience: 'Residents and local officials',
    tone: 'professional',
    structure: 'community-report',
    designPreset: 'rose-editorial',
    template: 'editorial-ivory',
    headingFont: 'Georgia',
    bodyFont: 'Aptos',
    density: 'airy',
    palette: { background: '#FDF2F8', surface: '#FBCFE8', text: '#500724', muted: '#9D174D', primary: '#831843', accent: '#EC4899' },
    orgName: 'Riverbend Council',
    subject: 'Housing, transit, and public space priorities'
  }
];

export const reportArchetypes: ReportArchetype[] = [...coreReportArchetypes, ...microsoftReportExpansions];

export const reportArchetypeIds = reportArchetypes.map((item) => item.id);