import type { ResumeArchetype } from './types.js';
import { microsoftResumeExpansions } from './microsoftArtifactExpansions.js';

const coreResumeArchetypes: ResumeArchetype[] = [
  {
    id: 'executive',
    title: 'Executive Leadership Resume',
    category: 'Executive resume',
    audience: 'Board recruiters and C-suite search firms',
    tone: 'executive',
    layout: 'executive',
    designPreset: 'executive-slate',
    template: 'executive-slate',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'airy',
    palette: { background: '#F8FAFC', surface: '#E7EDF4', text: '#0F172A', muted: '#64748B', primary: '#1E293B', accent: '#2563EB' },
    name: 'Elena Brooks',
    headline: 'VP Operations',
    role: 'Chief Operating Officer'
  },
  {
    id: 'creative',
    title: 'Creative Director Resume',
    category: 'Creative resume',
    audience: 'Creative agencies and brand studios',
    tone: 'professional',
    layout: 'creative',
    designPreset: 'bold-pop',
    template: 'bold-pop',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'airy',
    palette: { background: '#FFFFFF', surface: '#F3EFFF', text: '#14101F', muted: '#6E6781', primary: '#5B2EFF', accent: '#FF5C00' },
    name: 'Sam Ortiz',
    headline: 'Creative Director',
    role: 'Senior Brand Designer'
  },
  {
    id: 'technical',
    title: 'Platform Engineer Resume',
    category: 'Technical resume',
    audience: 'Engineering managers and staff recruiters',
    tone: 'professional',
    layout: 'technical',
    designPreset: 'midnight-aurora',
    template: 'midnight-aurora',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#0B1220', surface: '#16203A', text: '#E6EAF2', muted: '#8B94A8', primary: '#101A30', accent: '#2DD4BF' },
    name: 'Maya Rao',
    headline: 'Platform Engineer',
    role: 'Big Data Engineer'
  },
  {
    id: 'academic',
    title: 'Academic Research CV',
    category: 'Academic CV',
    audience: 'Faculty search committees',
    tone: 'professional',
    layout: 'academic',
    designPreset: 'editorial-ivory',
    template: 'editorial-ivory',
    headingFont: 'Georgia',
    bodyFont: 'Georgia',
    density: 'balanced',
    palette: { background: '#FBF8F1', surface: '#F0E9DB', text: '#221D15', muted: '#7A715F', primary: '#433A2B', accent: '#B5562C' },
    name: 'Dr. Priya Shah',
    headline: 'Assistant Professor',
    role: 'Computer Science Researcher'
  },
  {
    id: 'minimalist',
    title: 'Minimalist Professional Resume',
    category: 'Minimalist resume',
    audience: 'General hiring managers',
    tone: 'minimal',
    layout: 'minimalist',
    designPreset: 'consulting-mono',
    template: 'consulting-mono',
    headingFont: 'Arial',
    bodyFont: 'Arial',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#F2F2F1', text: '#121212', muted: '#6B6B6B', primary: '#1A1A1A', accent: '#C8102E' },
    name: 'Alex Morgan',
    headline: 'Operations Analyst',
    role: 'Business Operations Manager'
  },
  {
    id: 'two-column',
    title: 'Two-Column Resume',
    category: 'Two-column resume',
    audience: 'Recruiters scanning dense experience',
    tone: 'professional',
    layout: 'two-column',
    designPreset: 'modern-indigo',
    template: 'modern-indigo',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#EEF2FF', text: '#111827', muted: '#6B7280', primary: '#312E81', accent: '#4F46E5' },
    name: 'Jordan Lee',
    headline: 'Growth Marketing Lead',
    role: 'Social Media Manager'
  },
  {
    id: 'sidebar-skills',
    title: 'Sidebar Skills Resume',
    category: 'Sidebar resume',
    audience: 'Tech recruiters and hiring managers',
    tone: 'professional',
    layout: 'sidebar-skills',
    designPreset: 'cobalt-bold',
    template: 'cobalt-bold',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#E8EDFB', text: '#0A1633', muted: '#5A6685', primary: '#1D3FD8', accent: '#4D6FFF' },
    name: 'Riley Kim',
    headline: 'Technical Program Manager',
    role: 'TPM'
  },
  {
    id: 'designer',
    title: 'Product Designer Resume',
    category: 'Designer resume',
    audience: 'Design leads and product teams',
    tone: 'professional',
    layout: 'designer',
    designPreset: 'rose-editorial',
    template: 'editorial-ivory',
    headingFont: 'Georgia',
    bodyFont: 'Aptos',
    density: 'airy',
    palette: { background: '#FFF5F8', surface: '#FCE7F3', text: '#3F2D33', muted: '#9D7486', primary: '#831843', accent: '#F472B6' },
    name: 'Noah Vega',
    headline: 'Product Designer',
    role: 'Senior UX Designer'
  },
  {
    id: 'data-science',
    title: 'Data Scientist Resume',
    category: 'Data science resume',
    audience: 'ML and analytics hiring teams',
    tone: 'professional',
    layout: 'data-science',
    designPreset: 'teal-momentum',
    template: 'editorial-warm',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#F0FDFA', surface: '#CCFBF1', text: '#134E4A', muted: '#0F766E', primary: '#115E59', accent: '#14B8A6' },
    name: 'Aisha Patel',
    headline: 'Data Scientist',
    role: 'Senior ML Engineer'
  },
  {
    id: 'product',
    title: 'Product Manager Resume',
    category: 'Product resume',
    audience: 'Product leadership and founders',
    tone: 'professional',
    layout: 'product',
    designPreset: 'signal-orange',
    template: 'signal-orange',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#FFF1E8', text: '#23234B', muted: '#6F6F95', primary: '#FF5A1F', accent: '#32327A' },
    name: 'Chris Dalton',
    headline: 'Product Manager',
    role: 'Senior Product Manager'
  },
  {
    id: 'sales',
    title: 'Enterprise Sales Resume',
    category: 'Sales resume',
    audience: 'Sales directors and revenue leaders',
    tone: 'executive',
    layout: 'sales',
    designPreset: 'noir-lumina',
    template: 'noir-lumina',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#0A0A0C', surface: '#17171C', text: '#F2EFE9', muted: '#9A958C', primary: '#141419', accent: '#E8A33D' },
    name: 'Marcus Reed',
    headline: 'Enterprise Account Executive',
    role: 'Regional Sales Director'
  },
  {
    id: 'healthcare',
    title: 'Healthcare Administrator Resume',
    category: 'Healthcare resume',
    audience: 'Hospital administrators and clinic networks',
    tone: 'professional',
    layout: 'healthcare',
    designPreset: 'spreadsheet-forest',
    template: 'executive-slate',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#ECFDF5', text: '#052E1B', muted: '#4B6B5A', primary: '#217346', accent: '#34D399' },
    name: 'Dr. Lin Nguyen',
    headline: 'Clinical Operations Director',
    role: 'Healthcare Administrator'
  },
  {
    id: 'legal',
    title: 'Corporate Counsel Resume',
    category: 'Legal resume',
    audience: 'General counsel and law firm partners',
    tone: 'executive',
    layout: 'legal',
    designPreset: 'classic-ats',
    template: 'classic-ats',
    headingFont: 'Cambria',
    bodyFont: 'Cambria',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#F5F5F2', text: '#111111', muted: '#555555', primary: '#111111', accent: '#1F4E79' },
    name: 'Hannah Cole',
    headline: 'Corporate Counsel',
    role: 'Senior Associate Attorney'
  },
  {
    id: 'education',
    title: 'Teacher Resume',
    category: 'Education resume',
    audience: 'School districts and principals',
    tone: 'professional',
    layout: 'education',
    designPreset: 'editorial-warm',
    template: 'editorial-warm',
    headingFont: 'Georgia',
    bodyFont: 'Aptos',
    density: 'airy',
    palette: { background: '#F7F3EC', surface: '#EDE5D8', text: '#262220', muted: '#857B6E', primary: '#3E372F', accent: '#C96F4A' },
    name: 'Emily Torres',
    headline: 'High School Science Teacher',
    role: 'STEM Educator'
  },
  {
    id: 'architecture',
    title: 'Solutions Architect Resume',
    category: 'Architecture resume',
    audience: 'Enterprise architecture and cloud teams',
    tone: 'professional',
    layout: 'architecture',
    designPreset: 'spreadsheet-royal',
    template: 'modern-indigo',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#F5F3FF', text: '#2E1065', muted: '#7C6F9A', primary: '#6B46C1', accent: '#A78BFA' },
    name: 'David Okonkwo',
    headline: 'Solutions Architect',
    role: 'Principal Cloud Architect'
  },
  {
    id: 'consulting',
    title: 'Management Consultant Resume',
    category: 'Consulting resume',
    audience: 'Consulting partners and engagement managers',
    tone: 'executive',
    layout: 'consulting',
    designPreset: 'consulting-mono',
    template: 'consulting-mono',
    headingFont: 'Arial',
    bodyFont: 'Arial',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#F8FAFC', text: '#0F172A', muted: '#64748B', primary: '#334155', accent: '#DC2626' },
    name: 'Sophie Laurent',
    headline: 'Management Consultant',
    role: 'Senior Strategy Consultant'
  },
  {
    id: 'founder',
    title: 'Startup Founder Resume',
    category: 'Founder resume',
    audience: 'Investors and startup hiring teams',
    tone: 'executive',
    layout: 'founder',
    designPreset: 'lime-metric',
    template: 'bold-pop',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#F7FEE7', text: '#1A2E05', muted: '#4D7C0F', primary: '#65A30D', accent: '#F97316' },
    name: 'Tomas Alvarez',
    headline: 'Founder & CEO',
    role: 'Startup Founder'
  },
  {
    id: 'remote',
    title: 'Remote Specialist Resume',
    category: 'Remote resume',
    audience: 'Distributed teams and async-first companies',
    tone: 'professional',
    layout: 'remote',
    designPreset: 'modern-indigo',
    template: 'modern-indigo',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#F0F9FF', text: '#0C4A6E', muted: '#64748B', primary: '#0369A1', accent: '#38BDF8' },
    name: 'Casey Wu',
    headline: 'Remote Customer Success Lead',
    role: 'Customer Success Manager'
  },
  {
    id: 'career-change',
    title: 'Career Change Resume',
    category: 'Career change resume',
    audience: 'Hiring managers evaluating transferable skills',
    tone: 'professional',
    layout: 'career-change',
    designPreset: 'wellness-signal',
    template: 'signal-orange',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#FFF1E8', text: '#0F172A', muted: '#64748B', primary: '#FF5A1F', accent: '#1D4ED8' },
    name: 'Jamie Foster',
    headline: 'Transitioning to Product Operations',
    role: 'Product Operations Specialist'
  },
  {
    id: 'federal',
    title: 'Federal Government Resume',
    category: 'Federal resume',
    audience: 'Federal hiring managers and USAJOBS reviewers',
    tone: 'detailed',
    layout: 'federal',
    designPreset: 'classic-ats',
    template: 'classic-ats',
    headingFont: 'Cambria',
    bodyFont: 'Cambria',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#F1F5F9', text: '#0F172A', muted: '#475569', primary: '#1E293B', accent: '#1D4ED8' },
    name: 'Robert Hayes',
    headline: 'Program Analyst',
    role: 'Federal Program Manager'
  },
  {
    id: 'nursing',
    title: 'Registered Nurse Resume',
    category: 'Nursing resume',
    audience: 'Hospital HR and nursing directors',
    tone: 'professional',
    layout: 'nursing',
    designPreset: 'rose-editorial',
    template: 'editorial-ivory',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFF5F8', surface: '#FCE7F3', text: '#3F2D33', muted: '#9D7486', primary: '#831843', accent: '#F472B6' },
    name: 'Maria Santos',
    headline: 'Registered Nurse',
    role: 'ICU Charge Nurse'
  },
  {
    id: 'hospitality',
    title: 'Hospitality Manager Resume',
    category: 'Hospitality resume',
    audience: 'Hotel and restaurant group recruiters',
    tone: 'professional',
    layout: 'hospitality',
    designPreset: 'editorial-warm',
    template: 'editorial-warm',
    headingFont: 'Georgia',
    bodyFont: 'Aptos',
    density: 'airy',
    palette: { background: '#FFFBEB', surface: '#FEF3C7', text: '#78350F', muted: '#B45309', primary: '#92400E', accent: '#D97706' },
    name: 'Olivia Grant',
    headline: 'Hotel Operations Manager',
    role: 'Hospitality Director'
  },
  {
    id: 'engineering-lead',
    title: 'Engineering Lead Resume',
    category: 'Engineering lead resume',
    audience: 'VP Engineering and technical founders',
    tone: 'executive',
    layout: 'engineering-lead',
    designPreset: 'midnight-aurora',
    template: 'midnight-aurora',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#111827', surface: '#1F2937', text: '#F9FAFB', muted: '#9CA3AF', primary: '#030712', accent: '#22D3EE' },
    name: 'Nathan Brooks',
    headline: 'Engineering Manager',
    role: 'Director of Engineering'
  },
  {
    id: 'marketing',
    title: 'Marketing Manager Resume',
    category: 'Marketing resume',
    audience: 'CMOs and brand marketing leaders',
    tone: 'professional',
    layout: 'marketing',
    designPreset: 'bold-pop',
    template: 'bold-pop',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#FDF4FF', text: '#3B0764', muted: '#7E22CE', primary: '#6B21A8', accent: '#E879F9' },
    name: 'Taylor Nguyen',
    headline: 'Brand Marketing Manager',
    role: 'Marketing Manager'
  },
  {
    id: 'finance',
    title: 'Finance Analyst Resume',
    category: 'Finance resume',
    audience: 'CFO office and FP&A leaders',
    tone: 'professional',
    layout: 'finance',
    designPreset: 'executive-slate',
    template: 'executive-slate',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#F8FAFC', surface: '#E2E8F0', text: '#0F172A', muted: '#64748B', primary: '#1E293B', accent: '#10B981' },
    name: 'Alex Morgan',
    headline: 'Finance Analyst',
    role: 'FP&A Manager'
  },
  {
    id: 'campus',
    title: 'Campus Intern Resume',
    category: 'Campus resume',
    audience: 'Campus recruiters and internship coordinators',
    tone: 'campus',
    layout: 'campus',
    designPreset: 'modern-indigo',
    template: 'modern-indigo',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'airy',
    palette: { background: '#FFFFFF', surface: '#EDE9FE', text: '#4C1D95', muted: '#7C3AED', primary: '#5B21B6', accent: '#A78BFA' },
    name: 'Priya Shah',
    headline: 'CS Graduate',
    role: 'Software Engineer Intern'
  },
  {
    id: 'c-suite',
    title: 'C-Suite Executive Resume',
    category: 'C-suite resume',
    audience: 'Executive search firms and boards',
    tone: 'executive',
    layout: 'c-suite',
    designPreset: 'noir-lumina',
    template: 'noir-lumina',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'airy',
    palette: { background: '#0A0A0C', surface: '#17171C', text: '#F2EFE9', muted: '#9A958C', primary: '#141419', accent: '#E8A33D' },
    name: 'Victoria Chen',
    headline: 'Chief Revenue Officer',
    role: 'CRO'
  },
  {
    id: 'bilingual',
    title: 'Bilingual Professional Resume',
    category: 'Bilingual resume',
    audience: 'Global employers and localization teams',
    tone: 'professional',
    layout: 'bilingual',
    designPreset: 'cobalt-bold',
    template: 'cobalt-bold',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#EFF6FF', text: '#1E3A8A', muted: '#60A5FA', primary: '#1D4ED8', accent: '#F59E0B' },
    name: 'Isabella Ruiz',
    headline: 'Bilingual Customer Success Manager',
    role: 'Global Support Lead'
  },
  {
    id: 'contractor',
    title: 'Independent Contractor Resume',
    category: 'Contractor resume',
    audience: 'Clients and agency talent buyers',
    tone: 'professional',
    layout: 'contractor',
    designPreset: 'consulting-mono',
    template: 'consulting-mono',
    headingFont: 'Arial',
    bodyFont: 'Arial',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#FAFAFA', text: '#171717', muted: '#737373', primary: '#262626', accent: '#0EA5E9' },
    name: 'Avery Chen',
    headline: 'Freelance Consultant',
    role: 'Independent Contractor'
  },
  {
    id: 'nonprofit',
    title: 'Nonprofit Program Resume',
    category: 'Nonprofit resume',
    audience: 'Foundation program directors',
    tone: 'professional',
    layout: 'nonprofit',
    designPreset: 'editorial-warm',
    template: 'editorial-warm',
    headingFont: 'Georgia',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#F7F3EC', surface: '#EDE5D8', text: '#262220', muted: '#857B6E', primary: '#3E372F', accent: '#C96F4A' },
    name: 'Daniel Kim',
    headline: 'Program Director',
    role: 'Nonprofit Program Manager'
  },
  {
    id: 'research',
    title: 'Research Fellow Resume',
    category: 'Research resume',
    audience: 'Research labs and grant committees',
    tone: 'professional',
    layout: 'research',
    designPreset: 'editorial-ivory',
    template: 'editorial-ivory',
    headingFont: 'Georgia',
    bodyFont: 'Georgia',
    density: 'balanced',
    palette: { background: '#FBF8F1', surface: '#F0E9DB', text: '#221D15', muted: '#7A715F', primary: '#433A2B', accent: '#B5562C' },
    name: 'Dr. Amara Okafor',
    headline: 'Research Fellow',
    role: 'Postdoctoral Researcher'
  },
  {
    id: 'operations',
    title: 'Operations Manager Resume',
    category: 'Operations resume',
    audience: 'COO office and operations leaders',
    tone: 'professional',
    layout: 'operations',
    designPreset: 'spreadsheet-forest',
    template: 'executive-slate',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#ECFDF5', text: '#052E1B', muted: '#4B6B5A', primary: '#217346', accent: '#34D399' },
    name: 'Elena Brooks',
    headline: 'Operations Manager',
    role: 'Director of Operations'
  }
];

export const resumeArchetypes: ResumeArchetype[] = [...coreResumeArchetypes, ...microsoftResumeExpansions];

export const resumeArchetypeIds = resumeArchetypes.map((item) => item.id);