import type { SheetArchetype } from './types.js';
import { microsoftSheetExpansions } from './microsoftArtifactExpansions.js';

const coreSheetArchetypes: SheetArchetype[] = [
  {
    id: 'dashboard',
    title: 'Executive KPI Dashboard',
    category: 'Dashboard',
    audience: 'Leadership and operations',
    tone: 'executive',
    structure: 'dashboard',
    designPreset: 'lime-metric',
    template: 'bold-pop',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#F7FEE7', text: '#1A2E05', muted: '#4D7C0F', primary: '#65A30D', accent: '#F97316' },
    entity: 'Orion Labs'
  },
  {
    id: 'budget',
    title: 'Annual Budget Planner',
    category: 'Budget',
    audience: 'Finance and department heads',
    tone: 'professional',
    structure: 'budget',
    designPreset: 'spreadsheet-forest',
    template: 'executive-slate',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#ECFDF5', text: '#052E1B', muted: '#4B6B5A', primary: '#217346', accent: '#34D399' },
    entity: 'Northwind Holdings'
  },
  {
    id: 'pl-statement',
    title: 'Profit and Loss Statement',
    category: 'P&L',
    audience: 'CFO and finance analysts',
    tone: 'executive',
    structure: 'pl-statement',
    designPreset: 'executive-slate',
    template: 'executive-slate',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#F8FAFC', surface: '#E2E8F0', text: '#0F172A', muted: '#64748B', primary: '#1E293B', accent: '#2563EB' },
    entity: 'Brightline Commerce'
  },
  {
    id: 'cap-table',
    title: 'Cap Table Tracker',
    category: 'Cap table',
    audience: 'Founders and legal finance',
    tone: 'professional',
    structure: 'cap-table',
    designPreset: 'spreadsheet-royal',
    template: 'modern-indigo',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#F5F3FF', text: '#2E1065', muted: '#7C6F9A', primary: '#6B46C1', accent: '#A78BFA' },
    entity: 'Gridpulse'
  },
  {
    id: 'okr-tracker',
    title: 'OKR Tracker',
    category: 'OKR tracker',
    audience: 'Product and engineering leads',
    tone: 'professional',
    structure: 'okr-tracker',
    designPreset: 'cobalt-bold',
    template: 'cobalt-bold',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#E8EDFB', text: '#0A1633', muted: '#5A6685', primary: '#1D3FD8', accent: '#4D6FFF' },
    entity: 'Threadline'
  },
  {
    id: 'sales-pipeline',
    title: 'Sales Pipeline Tracker',
    category: 'Sales pipeline',
    audience: 'Sales managers and reps',
    tone: 'professional',
    structure: 'sales-pipeline',
    designPreset: 'signal-orange',
    template: 'signal-orange',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#FFF1E8', text: '#23234B', muted: '#6F6F95', primary: '#FF5A1F', accent: '#32327A' },
    entity: 'PeopleStack'
  },
  {
    id: 'inventory',
    title: 'Inventory Management Sheet',
    category: 'Inventory',
    audience: 'Warehouse and retail ops',
    tone: 'professional',
    structure: 'inventory',
    designPreset: 'spreadsheet-forest',
    template: 'executive-slate',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#F0FDF4', text: '#14532D', muted: '#166534', primary: '#15803D', accent: '#4ADE80' },
    entity: 'Shelfstack'
  },
  {
    id: 'expense-tracker',
    title: 'Team Expense Tracker',
    category: 'Expense tracker',
    audience: 'Managers and finance ops',
    tone: 'professional',
    structure: 'expense-tracker',
    designPreset: 'consulting-mono',
    template: 'consulting-mono',
    headingFont: 'Arial',
    bodyFont: 'Arial',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#F2F2F1', text: '#121212', muted: '#6B6B6B', primary: '#1A1A1A', accent: '#C8102E' },
    entity: 'Apex Revenue'
  },
  {
    id: 'project-timeline',
    title: 'Project Timeline Gantt',
    category: 'Project timeline',
    audience: 'PMO and project managers',
    tone: 'professional',
    structure: 'project-timeline',
    designPreset: 'modern-indigo',
    template: 'modern-indigo',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#EEF2FF', text: '#111827', muted: '#6B7280', primary: '#312E81', accent: '#4F46E5' },
    entity: 'Metro Facilities'
  },
  {
    id: 'headcount-plan',
    title: 'Headcount Planning Model',
    category: 'Headcount plan',
    audience: 'HR and finance planning',
    tone: 'executive',
    structure: 'headcount-plan',
    designPreset: 'executive-slate',
    template: 'executive-slate',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#F1F5F9', surface: '#CBD5E1', text: '#0F172A', muted: '#475569', primary: '#334155', accent: '#0EA5E9' },
    entity: 'Xboard HR'
  },
  {
    id: 'cash-flow',
    title: 'Cash Flow Forecast',
    category: 'Cash flow',
    audience: 'Treasury and FP&A',
    tone: 'executive',
    structure: 'cash-flow',
    designPreset: 'teal-momentum',
    template: 'editorial-warm',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#CCFBF1', text: '#134E4A', muted: '#0F766E', primary: '#115E59', accent: '#14B8A6' },
    entity: 'Ledgerlane'
  },
  {
    id: 'marketing-roi',
    title: 'Marketing ROI Calculator',
    category: 'Marketing ROI',
    audience: 'Growth and marketing ops',
    tone: 'professional',
    structure: 'marketing-roi',
    designPreset: 'bold-pop',
    template: 'bold-pop',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#FDF4FF', text: '#3B0764', muted: '#7E22CE', primary: '#6B21A8', accent: '#E879F9' },
    entity: 'Pulseform'
  },
  {
    id: 'customer-cohort',
    title: 'Customer Cohort Analysis',
    category: 'Customer cohort',
    audience: 'Product analytics teams',
    tone: 'professional',
    structure: 'customer-cohort',
    designPreset: 'cobalt-bold',
    template: 'cobalt-bold',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#DBEAFE', text: '#1E3A8A', muted: '#3B82F6', primary: '#1D4ED8', accent: '#06B6D4' },
    entity: 'Pulseboard'
  },
  {
    id: 'vendor-scorecard',
    title: 'Vendor Scorecard',
    category: 'Vendor scorecard',
    audience: 'Procurement and ops',
    tone: 'professional',
    structure: 'vendor-scorecard',
    designPreset: 'consulting-mono',
    template: 'consulting-mono',
    headingFont: 'Arial',
    bodyFont: 'Arial',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#FAFAFA', text: '#171717', muted: '#737373', primary: '#262626', accent: '#F59E0B' },
    entity: 'SupplyCo Partners'
  },
  {
    id: 'sprint-velocity',
    title: 'Sprint Velocity Tracker',
    category: 'Sprint velocity',
    audience: 'Engineering managers',
    tone: 'professional',
    structure: 'sprint-velocity',
    designPreset: 'lime-metric',
    template: 'bold-pop',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#ECFCCB', text: '#365314', muted: '#4D7C0F', primary: '#3F6212', accent: '#84CC16' },
    entity: 'Atlas Platform'
  },
  {
    id: 'content-calendar',
    title: 'Content Calendar',
    category: 'Content calendar',
    audience: 'Content and social teams',
    tone: 'professional',
    structure: 'content-calendar',
    designPreset: 'rose-editorial',
    template: 'editorial-ivory',
    headingFont: 'Georgia',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFF5F8', surface: '#FCE7F3', text: '#3F2D33', muted: '#9D7486', primary: '#831843', accent: '#F472B6' },
    entity: 'Harbor Press'
  },
  {
    id: 'attendance-log',
    title: 'Class Attendance Log',
    category: 'Attendance log',
    audience: 'Teachers and administrators',
    tone: 'professional',
    structure: 'attendance-log',
    designPreset: 'modern-indigo',
    template: 'modern-indigo',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#EDE9FE', text: '#4C1D95', muted: '#7C3AED', primary: '#5B21B6', accent: '#A78BFA' },
    entity: 'Campusflow'
  },
  {
    id: 'gradebook',
    title: 'Course Gradebook',
    category: 'Gradebook',
    audience: 'Instructors and registrars',
    tone: 'professional',
    structure: 'gradebook',
    designPreset: 'editorial-ivory',
    template: 'editorial-ivory',
    headingFont: 'Georgia',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#FBF8F1', surface: '#F0E9DB', text: '#221D15', muted: '#7A715F', primary: '#433A2B', accent: '#B5562C' },
    entity: 'Greenfield University'
  },
  {
    id: 'rental-ledger',
    title: 'Property Rental Ledger',
    category: 'Rental ledger',
    audience: 'Property managers',
    tone: 'professional',
    structure: 'rental-ledger',
    designPreset: 'editorial-warm',
    template: 'editorial-warm',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#F7F3EC', surface: '#EDE5D8', text: '#262220', muted: '#857B6E', primary: '#3E372F', accent: '#C96F4A' },
    entity: 'Summit Properties'
  },
  {
    id: 'maintenance-schedule',
    title: 'Equipment Maintenance Schedule',
    category: 'Maintenance schedule',
    audience: 'Facilities and maintenance crews',
    tone: 'professional',
    structure: 'maintenance-schedule',
    designPreset: 'spreadsheet-forest',
    template: 'executive-slate',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#DCFCE7', text: '#14532D', muted: '#166534', primary: '#166534', accent: '#22C55E' },
    entity: 'Evergreen Manufacturing'
  },
  {
    id: 'quote-estimator',
    title: 'Project Quote Estimator',
    category: 'Quote estimator',
    audience: 'Sales engineers and estimators',
    tone: 'professional',
    structure: 'quote-estimator',
    designPreset: 'signal-orange',
    template: 'signal-orange',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#FFEDD5', text: '#7C2D12', muted: '#C2410C', primary: '#EA580C', accent: '#1D4ED8' },
    entity: 'Brightline Studio'
  },
  {
    id: 'commission-calc',
    title: 'Sales Commission Calculator',
    category: 'Commission calc',
    audience: 'Sales ops and finance',
    tone: 'professional',
    structure: 'commission-calc',
    designPreset: 'executive-slate',
    template: 'executive-slate',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#E7EDF4', text: '#0F172A', muted: '#64748B', primary: '#1E293B', accent: '#10B981' },
    entity: 'Northstar CRM'
  },
  {
    id: 'fleet-dispatch',
    title: 'Fleet Dispatch Board',
    category: 'Fleet dispatch',
    audience: 'Dispatch coordinators',
    tone: 'professional',
    structure: 'fleet-dispatch',
    designPreset: 'midnight-aurora',
    template: 'midnight-aurora',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#0B1220', surface: '#16203A', text: '#E6EAF2', muted: '#8B94A8', primary: '#101A30', accent: '#2DD4BF' },
    entity: 'Routewise'
  },
  {
    id: 'recipe-costing',
    title: 'Recipe Costing Sheet',
    category: 'Recipe costing',
    audience: 'Restaurant managers and chefs',
    tone: 'professional',
    structure: 'recipe-costing',
    designPreset: 'editorial-warm',
    template: 'editorial-warm',
    headingFont: 'Georgia',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#FFFBEB', surface: '#FEF3C7', text: '#78350F', muted: '#B45309', primary: '#92400E', accent: '#D97706' },
    entity: 'Harbor Kitchen'
  },
  {
    id: 'donation-tracker',
    title: 'Donation Tracker',
    category: 'Donation tracker',
    audience: 'Nonprofit development teams',
    tone: 'professional',
    structure: 'donation-tracker',
    designPreset: 'rose-editorial',
    template: 'editorial-ivory',
    headingFont: 'Georgia',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFF5F8', surface: '#FCE7F3', text: '#3F2D33', muted: '#9D7486', primary: '#831843', accent: '#F472B6' },
    entity: 'Riverbend Foundation'
  },
  {
    id: 'event-budget',
    title: 'Event Budget Workbook',
    category: 'Event budget',
    audience: 'Event planners and marketing',
    tone: 'professional',
    structure: 'event-budget',
    designPreset: 'bold-pop',
    template: 'bold-pop',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#FFFFFF', surface: '#F3EFFF', text: '#14101F', muted: '#6E6781', primary: '#5B2EFF', accent: '#FF5C00' },
    entity: 'Futureworks'
  },
  {
    id: 'social-metrics',
    title: 'Social Media Metrics',
    category: 'Social metrics',
    audience: 'Social media managers',
    tone: 'professional',
    structure: 'social-metrics',
    designPreset: 'wellness-signal',
    template: 'signal-orange',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#FFF1E8', text: '#0F172A', muted: '#64748B', primary: '#FF5A1F', accent: '#1D4ED8' },
    entity: 'Jordan Lee Growth'
  },
  {
    id: 'risk-register',
    title: 'Project Risk Register',
    category: 'Risk register',
    audience: 'Risk and program managers',
    tone: 'professional',
    structure: 'risk-register',
    designPreset: 'consulting-mono',
    template: 'consulting-mono',
    headingFont: 'Arial',
    bodyFont: 'Arial',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#FEF2F2', text: '#7F1D1D', muted: '#B91C1C', primary: '#991B1B', accent: '#FBBF24' },
    entity: 'Sentinel Trust'
  },
  {
    id: 'asset-depreciation',
    title: 'Asset Depreciation Schedule',
    category: 'Asset depreciation',
    audience: 'Accounting and asset managers',
    tone: 'professional',
    structure: 'asset-depreciation',
    designPreset: 'spreadsheet-royal',
    template: 'modern-indigo',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#EEF2FF', text: '#1E1B4B', muted: '#6366F1', primary: '#4338CA', accent: '#818CF8' },
    entity: 'Atlas Devices'
  },
  {
    id: 'timesheet',
    title: 'Contractor Timesheet',
    category: 'Timesheet',
    audience: 'Contractors and project admins',
    tone: 'professional',
    structure: 'timesheet',
    designPreset: 'classic-ats',
    template: 'consulting-mono',
    headingFont: 'Cambria',
    bodyFont: 'Cambria',
    density: 'compact',
    palette: { background: '#FFFFFF', surface: '#F5F5F2', text: '#111111', muted: '#555555', primary: '#111111', accent: '#1F4E79' },
    entity: 'Avery Chen Consulting'
  },
  {
    id: 'price-comparison',
    title: 'Vendor Price Comparison',
    category: 'Price comparison',
    audience: 'Procurement analysts',
    tone: 'professional',
    structure: 'price-comparison',
    designPreset: 'executive-slate',
    template: 'executive-slate',
    headingFont: 'Aptos',
    bodyFont: 'Aptos',
    density: 'compact',
    palette: { background: '#F8FAFC', surface: '#E2E8F0', text: '#0F172A', muted: '#64748B', primary: '#1E40AF', accent: '#3B82F6' },
    entity: 'Metro Facilities'
  },
  {
    id: 'survey-results',
    title: 'Employee Survey Results',
    category: 'Survey results',
    audience: 'HR and people analytics',
    tone: 'professional',
    structure: 'survey-results',
    designPreset: 'teal-momentum',
    template: 'editorial-warm',
    headingFont: 'Aptos Display',
    bodyFont: 'Aptos',
    density: 'balanced',
    palette: { background: '#F0FDFA', surface: '#CCFBF1', text: '#134E4A', muted: '#0F766E', primary: '#115E59', accent: '#14B8A6' },
    entity: 'Helpline'
  }
];

export const sheetArchetypes: SheetArchetype[] = [...coreSheetArchetypes, ...microsoftSheetExpansions];

export const sheetArchetypeIds = sheetArchetypes.map((item) => item.id);